version: "3.8"
services:
  database:
    image: postgres
    container_name: local_waki_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - local_pgdata:/var/lib/postgresql/data

volumes:
  local_pgdata:
